"""category model 2

Revision ID: 4a20dfbe035a
Revises: f4010f838f0a
Create Date: 2022-04-15 14:33:02.204186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a20dfbe035a'
down_revision = 'f4010f838f0a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category'))
    )
    op.create_index('uq_cat_name', 'category', ['name'], unique=True, mysql_length=255)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_cat_name', table_name='category', mysql_length=255)
    op.drop_table('category')
    # ### end Alembic commands ###
