"""category model

Revision ID: f4010f838f0a
Revises: 197f438dbef3
Create Date: 2022-04-15 14:28:00.064215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4010f838f0a'
down_revision = '197f438dbef3'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('my_index', table_name='asset')
    op.create_index('uq_ass_name', 'asset', ['name'], unique=True, mysql_length=255)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_ass_name', table_name='asset', mysql_length=255)
    op.create_index('my_index', 'asset', ['name'], unique=False)
    # ### end Alembic commands ###
