"""category name not null

Revision ID: 5deca40304f4
Revises: 4a20dfbe035a
Create Date: 2022-04-17 17:55:54.816046

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5deca40304f4'
down_revision = '4a20dfbe035a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'name',
               existing_type=mysql.TEXT(),
               type_=sa.String(32),
               nullable=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'name',
               existing_type=sa.String(32),
               type_=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
